### ISSUE TITLE
List of opportunities for local civic involvement

### ISSUE THREAD

**Issue by sethetter** [openwichita/project-ideas#5]
Some web service showing a list of local committee meetings, council meetings, etc, that are open to the public. The idea is to be an easy place for someone to come to who wants to get involved with the city but don't know where to start or find that information.

I think a lot of this information could be scraped from certain websites so it's all kept up to date.

Simplicity is key!

**Comment by infernocloud** [comment]
We should definitely have a webpage list of these, but in addition I think an open data calendar format (.ics) would be great to have so people can add these to their calendar of choice.

https://en.wikipedia.org/wiki/ICalendar

**Comment by Mearnest** [comment]
I'll start by look into scraping the content. The scraper will create a JSON file consumable by the web service.

**Comment by sethetter** [comment]
@Mearnest awesome! I'll get you added to the repo, you can do the work in here.

**Comment by sethetter** [comment]
@Mearnest github.com/openwichita/public-meetings

**Comment by Mearnest** [comment]
@sethetter I got distracted with other stuff. Question is whether to go forward with this project, or just ask the city to upload the schedule to wichita.gov in an html format. Does another website with the schedule add value beyond a better format than a PDF? I played around with scraping the two meetings PDF in Python, and that's totally doable. But then if the PDF only changes once a year, is it worth it? So what is the value of the additional website? A means to add meetings to your calendar? Can the city do that with an html version of the meetings?

I reviewed this with Jason Vandecreek, and his thought was that wichita.gov already has all the relevant metting information, they just need a better format than a PDF. 

If another website is worth doing, then I'll start back on this tonight.

**Comment by sethetter** [comment]
@Mearnest I'm not sure that wichita.gov has *all* the relevant meeting information. We've actually began discussing this project in Slack during the last couple virtual hack nights. There's a local individual who keeps track of all these meetings who has been very helpful in sharing the information he has. The idea will be a database driven website to display this information and serve an ical feed. The database can be populated by scrapers, but also allowing manual entry.

**Comment by Mearnest** [comment]
@sethetter That makes sense. I'll look at the meeting info you have listed so far, and the web scraping side of things.
