### ISSUE TITLE
Voterfile Database

### ISSUE THREAD

**Issue by KSVotes** [openwichita/project-ideas#7]
### What problem are we trying to solve?

Kansas ranks #29 in the US on voter registration, and #36 in voter participation. Beyond the overall numbers, voting and registration among young people and the Black and Latino/a communities in Kansas is well below the U.S. average in those demographics. Kansas has adopted policies that require voters to submit proof of citizenship in order to be able to legally vote, making it more difficult for eligible voters to participate in the democratic process. Though the information is public, no one has done analytics on the effects of these policies on voters and voting in the state.

### Who will benefit (directly and indirectly) from this project?

Any potential voters or attempted registrations who have been purged or disqualified by the proof of citizenship requirements, and people interested in making sure that voting is accessible to everyone.

### What are the next steps (validation, research, coding, design)? 

Set up an AWS/Postgres instance of a db to load multiple versions of a 2M voter data set so that we can do some analysis of differences in datasets.  It should be multi-user accessible for research purposes which means there needs to be restrictions on what users can do (read-only for most users).   Additional connections for:
- Q-GIS visualization
- R/R-studio for analytics

### What help is needed at this time?

Building the database.

**Comment by karmadog** [comment]
I'm pretty rusty, but I used to build a lot of Access databases, and I've had classes in Oracle both command line and gui.  So I would be happy to try to work on a database, but I will have to learn the tool first probably.  Which database tool did you want to use?

**Comment by KSVotes** [comment]
Hey! We've actually gotten some work on this (I probably need to update or take down this post)....we'll keep you posted on what we need moving forward! Thanks!
