### ISSUE TITLE
Browser plugin to highlight links on a page that have snopes entries

### ISSUE THREAD

**Issue by sethetter** [openwichita/project-ideas#7]
It would be great to make it easier for people to be aware of potentially false or fake content online as they're browsing.

**Comment by adammessinger** [comment]
This is a great idea! These sources that flag entire sites as false or biased might simplify things for the worst offenders:

* [Fake News Watch](http://fakenewswatch.com/)
* [Media Bias/Fact Check](https://mediabiasfactcheck.com/) -- Might flag things on the far left/right as worth additional investigation, while [fake/satire sites](https://mediabiasfactcheck.com/satire/) get flagged as such. [Here's some info on the site's methodology](https://mediabiasfactcheck.com/methodology/), which also explains the kinds of bias they look for.
* [Snopes's own fake new site list](http://www.snopes.com/2016/01/14/fake-news-sites/)

For debunking specific news items, [FactCheck.org](http://www.factcheck.org/) might be a useful supplement to Snopes.

**Comment by sethetter** [comment]
Sounds like there's plenty of existing efforts for this! Closing for now.
